name: Lean

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: leanprover/lean-action@50fcf42d2e460296f1a34b402e990d1b24f8b596 # v1
        with:
          auto-config: "false"
          build: "true"
          test: "false"
          lint: "false"
          use-mathlib-cache: "true"
      - name: Check theorem dependencies
        run: lake env lean -DwarningAsError=true Check.lean
